[Feature] added authorized_key arg to rescue command
aszlig/hetzner pull request #47
Opened 2021-12-02 06:12 UTC by acjohnson

I've added the `--authorized-key` argument to the rescue command. Since this is already supported in the SDK/API I see no reason to skip this as a feature.

Thanks!

2021-12-10 05:55 UTC, aszlig requested changes
Thanks a lot. However this introduces an API incompatibility, since it changes the argument type of `RescueSystem.activate`.

2021-12-10 05:55 UTC, aszlig commented on hetzner/server.py
> +                opts['authorized_key'] = authorized_keys.split()
Note the docstring of this function:

> Note that 'authorized_keys', if passed, **must be a list** of fingerprints, e.g. `['a3:14:62:38:d1:45:35:6c:de:ad:ec:12:be:93:24:ef']`

2021-12-10 05:55 UTC, aszlig commented on hetznerctl
> +                                        " have been added to robot already")),
Using [`nargs`](https://docs.python.org/3/library/argparse.html#nargs) should get rid of the need to `split` anything and we should get a list as needed by the API.

```suggestion
        make_option('-a', '--authorized-key', dest='authkeys', metavar='AUTHKEY',
                    nargs='*', help=("md5 fingerprint of the key that should"
                                     " have been added to robot already")),
```

2021-12-11 03:24 UTC, acjohnson commented on hetznerctl
> +                                        " have been added to robot already")),
The problem with `nargs='*'` is that you can't place it before the `IP` positional argument. Per the docs though it looks like `nargs=1` is the way to go:

> Note that nargs=1 produces a list of one item. This is different from the default, in which the item is produced by itself.

https://docs.python.org/3/library/argparse.html#nargs

2021-12-11 03:37 UTC, acjohnson commented
aight it's a bit cleaner now

2022-01-22 13:35 UTC, acjohnson commented
@aszlig can this get merged now?

2022-07-27 14:26 UTC, acjohnson commented
@aszlig is there anything controversial about this PR that is keeping it from being merged? Happy to address. Thanks!

2022-07-27 15:47 UTC, merged

2022-07-27 15:49 UTC, aszlig commented
@acjohnson: Ah, no, there isn't (except a few nits which I addressed in https://github.com/aszlig/hetzner/commit/3fd8c5f9a0b033bd3ee368ab5b0de627573ae438), for some reason I keep missing notifications here. Thanks a lot!